apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  pgsql-password: VGVzdDEyMz0=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      imagePullSecrets:
        - name: gavinc-registry
      containers:
        - name: express-container
          image: registry.gavinc.be/gre:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pgsql-password
            - name: DB_NAME
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
      app: express
      env: prod
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30080
